### PR TITLE
Implement Heart Rate transformation.

### PR DESCRIPTION
**Pull request by brandonpollett**

### CODE REVIEW

**Comment by HATIMS** [comment]
>         public static readonly Coding BodyWeight = new Coding()

are you missing the () for HeartRate coding?

---
Refers to: Microsoft.HealthVault.Fhir/Codes/HealthVault/HealthVaultVitalStatisticsCodes.cs:21 in a916e6e. [](commit_id = a916e6e8a9454479d7d28497f597e0729e3bbae2, deletion_comment = False)

**Comment by HATIMS** [comment]
>         public static CodeableConcept BodyWeight = new CodeableConcept()

same as before

---
Refers to: Microsoft.HealthVault.Fhir/Constants/HealthVaultVocabularies.cs:35 in a916e6e. [](commit_id = a916e6e8a9454479d7d28497f597e0729e3bbae2, deletion_comment = False)

**Comment by HATIMS** [comment]
:shipit:

**Comment by gcorvera** [comment]
:shipit:

**Pull request merged**
